// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Navigation → Company Links*
 */
export interface NavigationDocumentDataFooterCompanyLinksItem {
  /**
   * Label field in *Navigation → Company Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerCompanyLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Company Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerCompanyLinks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Navigation → Legal Links*
 */
export interface NavigationDocumentDataFooterLegalLinksItem {
  /**
   * Label field in *Navigation → Legal Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerLegalLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Legal Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerLegalLinks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Navigation → Social Media*
 */
export interface NavigationDocumentDataFooterSocialMediaItem {
  /**
   * Name field in *Navigation → Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerSocialMedia[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerSocialMedia[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *Navigation → Social Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerSocialMedia[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>> /**
   * Company Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerCompanyLinks[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  footerCompanyLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataFooterCompanyLinksItem>
  >;

  /**
   * Legal Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerLegalLinks[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footerLegalLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataFooterLegalLinksItem>
  >;

  /**
   * Social Media field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerSocialMedia[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footerSocialMedia: prismic.GroupField<
    Simplify<NavigationDocumentDataFooterSocialMediaItem>
  >;

  /**
   * Newsletter Links field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footerNewsletterLinks
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footerNewsletterLinks: prismic.LinkField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | SimpleTextSlice
  | GridLayoutSlice
  | FeatureSlice
  | PhotoGallerySlice
  | TestimonialSlice
  | PricingSlice
  | ImageDownloadSlice
  | ImageWithTextSlice
  | BannerSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.metaTitle
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaTitle: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.metaDescription
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaImage
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Company Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.companyLogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  companyLogo: prismic.ImageField<never>;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  siteTitle: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.metaDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.ogImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ogImage: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Heading field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bold only the word(s) to be given the graident colour.
   * - **API ID Path**: banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Text field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Illustration One field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.illustrationOne
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustrationOne: prismic.ImageField<never>;

  /**
   * Illustration Two field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.illustrationTwo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustrationTwo: prismic.ImageField<never>;
}

/**
 * Call To Action variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceFeatureItem {
  /**
   * Image field in *Banner → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Banner → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Banner → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Feature variation for Banner Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceFeature = prismic.SharedSliceVariation<
  "feature",
  Record<string, never>,
  Simplify<BannerSliceFeatureItem>
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault | BannerSliceFeature;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *Feature → Primary*
 */
export interface FeatureSliceDefaultPrimary {
  /**
   * Heading field in *Feature → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Feature → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Subheading Background Colour field in *Feature → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Orange
   * - **API ID Path**: feature.primary.subheadingBackgroundColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  subheadingBackgroundColour: prismic.SelectField<
    "Orange" | "Purple" | "Blue" | "Lavendar" | "Green",
    "filled"
  >;

  /**
   * Body field in *Feature → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Body Background Colour field in *Feature → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Orange
   * - **API ID Path**: feature.primary.bodyBackgroundColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bodyBackgroundColour: prismic.SelectField<
    "Orange" | "Purple" | "Blue" | "Green" | "Lavender",
    "filled"
  >;

  /**
   * Image One field in *Feature → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.imageOne
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageOne: prismic.ImageField<never>;

  /**
   * Image Two field in *Feature → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.imageTwo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageTwo: prismic.ImageField<never>;

  /**
   * Illustration field in *Feature → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Background Spot Colour field in *Feature → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: feature.primary.backgroundSpotColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundSpotColour: prismic.SelectField<
    "None" | "Orange" | "Purple" | "Blue" | "Green" | "Lavender",
    "filled"
  >;
}

/**
 * Grid variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feature*
 */
type FeatureSliceVariation = FeatureSliceDefault;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSlice = prismic.SharedSlice<
  "feature",
  FeatureSliceVariation
>;

/**
 * Primary content in *GridLayout → Primary*
 */
export interface GridLayoutSliceDefaultPrimary {
  /**
   * Heading field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Background field in *GridLayout → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: grid_layout.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Background Colour field in *GridLayout → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.backgroundColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColour: prismic.SelectField<
    "None" | "Orange" | "Purple" | "Blue" | "Lavender"
  >;
}

/**
 * Primary content in *GridLayout → Items*
 */
export interface GridLayoutSliceDefaultItem {
  /**
   * Card Image field in *GridLayout → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardImage: prismic.ImageField<never>;

  /**
   * Card Heading field in *GridLayout → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardHeading: prismic.TitleField;

  /**
   * Card Body field in *GridLayout → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardBody: prismic.RichTextField;

  /**
   * Card Link field in *GridLayout → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cardLink: prismic.LinkField;
}

/**
 * Image with Text variation for GridLayout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridLayoutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridLayoutSliceDefaultPrimary>,
  Simplify<GridLayoutSliceDefaultItem>
>;

/**
 * Primary content in *GridLayout → Primary*
 */
export interface GridLayoutSliceIconWithTextPrimary {
  /**
   * Heading field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Background field in *GridLayout → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: grid_layout.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Background/Spot Colour field in *GridLayout → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.backgroundSpotColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundSpotColour: prismic.SelectField<
    "None" | "Orange" | "Purple" | "Blue" | "Lavender"
  >;
}

/**
 * Primary content in *GridLayout → Items*
 */
export interface GridLayoutSliceIconWithTextItem {
  /**
   * Card Icon field in *GridLayout → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardIcon: prismic.ImageField<never>;

  /**
   * Card Heading field in *GridLayout → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardHeading: prismic.TitleField;

  /**
   * card Body field in *GridLayout → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardBody: prismic.RichTextField;

  /**
   * Card Button Label field in *GridLayout → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardButtonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardButtonLabel: prismic.KeyTextField;

  /**
   * Card Button Link field in *GridLayout → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardButtonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cardButtonLink: prismic.LinkField;
}

/**
 * Icon with Text variation for GridLayout Slice
 *
 * - **API ID**: `iconWithText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridLayoutSliceIconWithText = prismic.SharedSliceVariation<
  "iconWithText",
  Simplify<GridLayoutSliceIconWithTextPrimary>,
  Simplify<GridLayoutSliceIconWithTextItem>
>;

/**
 * Primary content in *GridLayout → Primary*
 */
export interface GridLayoutSliceTheBigOnePrimary {
  /**
   * Heading field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * CTA Button Label field in *GridLayout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.ctaButtonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctaButtonLabel: prismic.KeyTextField;

  /**
   * CTA Button Link field in *GridLayout → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.ctaButtonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctaButtonLink: prismic.LinkField;

  /**
   * Timetable Heading field in *GridLayout → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.timetableHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  timetableHeading: prismic.TitleField;

  /**
   * Timetable Body field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.timetableBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  timetableBody: prismic.RichTextField;

  /**
   * Timetable January Link field in *GridLayout → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.timetableJanuaryLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  timetableJanuaryLink: prismic.LinkToMediaField;

  /**
   * Timetable February Link field in *GridLayout → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.timetableFebruaryLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  timetableFebruaryLink: prismic.LinkToMediaField;

  /**
   * Timetable March Link field in *GridLayout → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.timetableMarchLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  timetableMarchLink: prismic.LinkToMediaField;

  /**
   * Timetable April Link field in *GridLayout → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.timetableAprilLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  timetableAprilLink: prismic.LinkToMediaField;

  /**
   * Yearly Schedule Heading field in *GridLayout → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.yearlyScheduleHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  yearlyScheduleHeading: prismic.TitleField;

  /**
   * Yearly Schedule Body field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.yearlyScheduleBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  yearlyScheduleBody: prismic.RichTextField;

  /**
   * Yearly Schedule Image field in *GridLayout → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.yearlyScheduleImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  yearlyScheduleImage: prismic.ImageField<never>;
}

/**
 * Primary content in *GridLayout → Items*
 */
export interface GridLayoutSliceTheBigOneItem {
  /**
   * Class Card Image field in *GridLayout → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].classCardImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  classCardImage: prismic.ImageField<never>;

  /**
   * Class Card Heading field in *GridLayout → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].classCardHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  classCardHeading: prismic.TitleField;

  /**
   * Class Card Body field in *GridLayout → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].classCardBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  classCardBody: prismic.RichTextField;

  /**
   * Class Card Link field in *GridLayout → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].classCardLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  classCardLink: prismic.LinkField;

  /**
   * Class Card Background Colour field in *GridLayout → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].classCardBgColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  classCardBgColour: prismic.SelectField<
    "None" | "Orange" | "Blue" | "Purple" | "Green" | "Lavender" | "Peach"
  >;
}

/**
 * The Big One variation for GridLayout Slice
 *
 * - **API ID**: `theBigOne`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridLayoutSliceTheBigOne = prismic.SharedSliceVariation<
  "theBigOne",
  Simplify<GridLayoutSliceTheBigOnePrimary>,
  Simplify<GridLayoutSliceTheBigOneItem>
>;

/**
 * Primary content in *GridLayout → Primary*
 */
export interface GridLayoutSliceBentoLayoutOnePrimary {
  /**
   * Heading field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *GridLayout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *GridLayout → Items*
 */
export interface GridLayoutSliceBentoLayoutOneItem {
  /**
   * Card Image field in *GridLayout → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardImage: prismic.ImageField<never>;

  /**
   * Card Heading field in *GridLayout → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardHeading: prismic.TitleField;

  /**
   * Card Body field in *GridLayout → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardBody: prismic.RichTextField;

  /**
   * Card Link field in *GridLayout → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_layout.items[].cardLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cardLink: prismic.LinkField;
}

/**
 * Bento Layout One variation for GridLayout Slice
 *
 * - **API ID**: `bentoLayoutOne`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridLayoutSliceBentoLayoutOne = prismic.SharedSliceVariation<
  "bentoLayoutOne",
  Simplify<GridLayoutSliceBentoLayoutOnePrimary>,
  Simplify<GridLayoutSliceBentoLayoutOneItem>
>;

/**
 * Slice variation for *GridLayout*
 */
type GridLayoutSliceVariation =
  | GridLayoutSliceDefault
  | GridLayoutSliceIconWithText
  | GridLayoutSliceTheBigOne
  | GridLayoutSliceBentoLayoutOne;

/**
 * GridLayout Shared Slice
 *
 * - **API ID**: `grid_layout`
 * - **Description**: GridLayout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridLayoutSlice = prismic.SharedSlice<
  "grid_layout",
  GridLayoutSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Sticker field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageSticker
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageSticker: prismic.ImageField<never>;
}

/**
 * Stacked variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceBentoPrimary {
  /**
   * Main: Heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Main: Body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Main: Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Main: Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Main: Illustration field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Category 1: Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titleCatOne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleCatOne: prismic.KeyTextField;

  /**
   * Category 1: Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageCatOne
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageCatOne: prismic.ImageField<never>;

  /**
   * Category 1: Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLinkCatOne
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLinkCatOne: prismic.LinkField;

  /**
   * Category 2: Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titleCatTwo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleCatTwo: prismic.KeyTextField;

  /**
   * Category 2: Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageCatTwo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageCatTwo: prismic.ImageField<never>;

  /**
   * Category 2: Illustration field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.illustrationCatTwo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustrationCatTwo: prismic.ImageField<never>;

  /**
   * Category 2: Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLinkCatTwo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLinkCatTwo: prismic.LinkField;

  /**
   * Category 3: Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titleCatThree
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titleCatThree: prismic.KeyTextField;

  /**
   * Category 3: Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageCatThree
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageCatThree: prismic.ImageField<never>;

  /**
   * Category 3: Illustration field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.illustrationCatThree
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustrationCatThree: prismic.ImageField<never>;

  /**
   * Category 3: Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLinkCatThree
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLinkCatThree: prismic.LinkField;
}

/**
 * Bento variation for Hero Slice
 *
 * - **API ID**: `bento`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceBento = prismic.SharedSliceVariation<
  "bento",
  Simplify<HeroSliceBentoPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceLayeredPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Small field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imageSmall
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageSmall: prismic.ImageField<never>;

  /**
   * Illustration One field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.illustrationOne
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustrationOne: prismic.ImageField<never>;

  /**
   * Illustration Two field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.illustrationTwo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustrationTwo: prismic.ImageField<never>;
}

/**
 * Layered variation for Hero Slice
 *
 * - **API ID**: `layered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceLayered = prismic.SharedSliceVariation<
  "layered",
  Simplify<HeroSliceLayeredPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceAccordionPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * illustration field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceAccordionItem {
  /**
   * Accordion: Heading field in *Hero → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Accordion: Body field in *Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Accordion: Button Link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Accordion: Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Accordion variation for Hero Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceAccordion = prismic.SharedSliceVariation<
  "accordion",
  Simplify<HeroSliceAccordionPrimary>,
  Simplify<HeroSliceAccordionItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceBento
  | HeroSliceLayered
  | HeroSliceAccordion;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageDownload → Primary*
 */
export interface ImageDownloadSliceDefaultPrimary {
  /**
   * Heading field in *ImageDownload → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_download.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ImageDownload → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_download.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *ImageDownload → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_download.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Label field in *ImageDownload → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_download.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button Link field in *ImageDownload → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_download.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Default variation for ImageDownload Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageDownloadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageDownloadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageDownload*
 */
type ImageDownloadSliceVariation = ImageDownloadSliceDefault;

/**
 * ImageDownload Shared Slice
 *
 * - **API ID**: `image_download`
 * - **Description**: ImageDownload
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageDownloadSlice = prismic.SharedSlice<
  "image_download",
  ImageDownloadSliceVariation
>;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Section Reference Id field in *ImageWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Used only to reference this section to allow page jumping
   * - **API ID Path**: image_with_text.primary.sectionReferenceId
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectionReferenceId: prismic.KeyTextField;

  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *ImageWithText → Items*
 */
export interface ImageWithTextSliceDefaultItem {
  /**
   * Button Label field in *ImageWithText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button Link field in *ImageWithText → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  Simplify<ImageWithTextSliceDefaultItem>
>;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceImageRightPrimary {
  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Section Reference Id field in *ImageWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Used only to reference this section to allow page jumping
   * - **API ID Path**: image_with_text.primary.sectionReferenceId
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectionReferenceId: prismic.KeyTextField;
}

/**
 * Primary content in *ImageWithText → Items*
 */
export interface ImageWithTextSliceImageRightItem {
  /**
   * Button Label field in *ImageWithText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button Link field in *ImageWithText → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Image Right variation for ImageWithText Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<ImageWithTextSliceImageRightPrimary>,
  Simplify<ImageWithTextSliceImageRightItem>
>;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceImageLeftWithBackgroundPrimary {
  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Background Colour Orange field in *ImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_with_text.primary.backgroundColourOrange
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  backgroundColourOrange: prismic.BooleanField;

  /**
   * Background Colour Blue field in *ImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.primary.backgroundColourBlue
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  backgroundColourBlue: prismic.BooleanField;

  /**
   * Background Colour Purple field in *ImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.primary.backgroundColourPurple
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  backgroundColourPurple: prismic.BooleanField;

  /**
   * Background Colour field in *ImageWithText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Orange
   * - **API ID Path**: image_with_text.primary.backgroundColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColour: prismic.SelectField<
    "Orange" | "Blue" | "Purple" | "Lavender" | "Sage",
    "filled"
  >;
}

/**
 * Primary content in *ImageWithText → Items*
 */
export interface ImageWithTextSliceImageLeftWithBackgroundItem {
  /**
   * Button Label field in *ImageWithText → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button Link field in *ImageWithText → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Image Left with Background variation for ImageWithText Slice
 *
 * - **API ID**: `imageLeftWithBackground`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceImageLeftWithBackground =
  prismic.SharedSliceVariation<
    "imageLeftWithBackground",
    Simplify<ImageWithTextSliceImageLeftWithBackgroundPrimary>,
    Simplify<ImageWithTextSliceImageLeftWithBackgroundItem>
  >;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceImageRightLargePrimary {
  /**
   * Heading field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Background field in *ImageWithText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField;

  /**
   * Background Colour field in *ImageWithText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: image_with_text.primary.backgroundColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColour: prismic.SelectField<
    "None" | "Orange" | "Purple" | "Blue" | "Lavender",
    "filled"
  >;

  /**
   * Illustration field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Button Label field in *ImageWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button Link field in *ImageWithText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Primary content in *ImageWithText → Items*
 */
export interface ImageWithTextSliceImageRightLargeItem {
  /**
   * Image field in *ImageWithText → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Right Large variation for ImageWithText Slice
 *
 * - **API ID**: `imageRightLarge`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceImageRightLarge = prismic.SharedSliceVariation<
  "imageRightLarge",
  Simplify<ImageWithTextSliceImageRightLargePrimary>,
  Simplify<ImageWithTextSliceImageRightLargeItem>
>;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation =
  | ImageWithTextSliceDefault
  | ImageWithTextSliceImageRight
  | ImageWithTextSliceImageLeftWithBackground
  | ImageWithTextSliceImageRightLarge;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Primary content in *PhotoGallery → Primary*
 */
export interface PhotoGallerySliceDefaultPrimary {
  /**
   * Heading field in *PhotoGallery → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_gallery.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *PhotoGallery → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_gallery.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *PhotoGallery → Items*
 */
export interface PhotoGallerySliceDefaultItem {
  /**
   * Image field in *PhotoGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Horizontal variation for PhotoGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhotoGallerySliceDefaultPrimary>,
  Simplify<PhotoGallerySliceDefaultItem>
>;

/**
 * Primary content in *PhotoGallery → Primary*
 */
export interface PhotoGallerySliceVerticalPrimary {
  /**
   * Heading field in *PhotoGallery → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_gallery.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *PhotoGallery → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_gallery.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *PhotoGallery → Items*
 */
export interface PhotoGallerySliceVerticalItem {
  /**
   * Image field in *PhotoGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Vertical variation for PhotoGallery Slice
 *
 * - **API ID**: `vertical`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoGallerySliceVertical = prismic.SharedSliceVariation<
  "vertical",
  Simplify<PhotoGallerySliceVerticalPrimary>,
  Simplify<PhotoGallerySliceVerticalItem>
>;

/**
 * Slice variation for *PhotoGallery*
 */
type PhotoGallerySliceVariation =
  | PhotoGallerySliceDefault
  | PhotoGallerySliceVertical;

/**
 * PhotoGallery Shared Slice
 *
 * - **API ID**: `photo_gallery`
 * - **Description**: PhotoGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoGallerySlice = prismic.SharedSlice<
  "photo_gallery",
  PhotoGallerySliceVariation
>;

/**
 * Primary content in *Pricing → Primary*
 */
export interface PricingSliceDefaultPrimary {
  /**
   * Heading field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Pricing → Items*
 */
export interface PricingSliceDefaultItem {
  /**
   * Category field in *Pricing → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: pricing.items[].category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    "None" | "Non-member" | "Member" | "Monthly" | "Yearly",
    "filled"
  >;

  /**
   * Price Plan Heading field in *Pricing → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].pricePlanHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pricePlanHeading: prismic.RichTextField;

  /**
   * Price Plan Body field in *Pricing → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].pricePlanBody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pricePlanBody: prismic.RichTextField;

  /**
   * Pricing Model field in *Pricing → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].pricingModel
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  pricingModel: prismic.SelectField<"Daily" | "Weekly" | "Monthly" | "Yearly">;

  /**
   * Price field in *Pricing → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Start Time field in *Pricing → Items*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].startTime
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  startTime: prismic.TimestampField;

  /**
   * Finish Time field in *Pricing → Items*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].finishTime
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  finishTime: prismic.TimestampField;

  /**
   * Button Label One field in *Pricing → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].buttonLabelOne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabelOne: prismic.KeyTextField;

  /**
   * Button Link One field in *Pricing → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].buttonLinkOne
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLinkOne: prismic.LinkField;

  /**
   * Button Label Two field in *Pricing → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].buttonLabelTwo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabelTwo: prismic.KeyTextField;

  /**
   * Button Link Two field in *Pricing → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].buttonLinkTwo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLinkTwo: prismic.LinkField;
}

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingSliceDefaultPrimary>,
  Simplify<PricingSliceDefaultItem>
>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSlice = prismic.SharedSlice<
  "pricing",
  PricingSliceVariation
>;

/**
 * Primary content in *SimpleText → Primary*
 */
export interface SimpleTextSliceDefaultPrimary {
  /**
   * Heading field in *SimpleText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *SimpleText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for SimpleText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleText*
 */
type SimpleTextSliceVariation = SimpleTextSliceDefault;

/**
 * SimpleText Shared Slice
 *
 * - **API ID**: `simple_text`
 * - **Description**: SimpleText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSlice = prismic.SharedSlice<
  "simple_text",
  SimpleTextSliceVariation
>;

/**
 * Primary content in *Testimonial → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Heading field in *Testimonial → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Testimonial → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * testi field in *Testimonial → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.primary.testi
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testi: prismic.ContentRelationshipField<"testi">;
}

/**
 * Primary content in *Testimonial → Items*
 */
export interface TestimonialSliceDefaultItem {
  /**
   * Testimonial field in *Testimonial → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testimonial: prismic.ContentRelationshipField<"testimonial">;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  Simplify<TestimonialSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      NavigationDocumentDataFooterCompanyLinksItem,
      NavigationDocumentDataFooterLegalLinksItem,
      NavigationDocumentDataFooterSocialMediaItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceFeatureItem,
      BannerSliceVariation,
      BannerSliceDefault,
      BannerSliceFeature,
      FeatureSlice,
      FeatureSliceDefaultPrimary,
      FeatureSliceVariation,
      FeatureSliceDefault,
      GridLayoutSlice,
      GridLayoutSliceDefaultPrimary,
      GridLayoutSliceDefaultItem,
      GridLayoutSliceIconWithTextPrimary,
      GridLayoutSliceIconWithTextItem,
      GridLayoutSliceTheBigOnePrimary,
      GridLayoutSliceTheBigOneItem,
      GridLayoutSliceBentoLayoutOnePrimary,
      GridLayoutSliceBentoLayoutOneItem,
      GridLayoutSliceVariation,
      GridLayoutSliceDefault,
      GridLayoutSliceIconWithText,
      GridLayoutSliceTheBigOne,
      GridLayoutSliceBentoLayoutOne,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceBentoPrimary,
      HeroSliceLayeredPrimary,
      HeroSliceAccordionPrimary,
      HeroSliceAccordionItem,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceBento,
      HeroSliceLayered,
      HeroSliceAccordion,
      ImageDownloadSlice,
      ImageDownloadSliceDefaultPrimary,
      ImageDownloadSliceVariation,
      ImageDownloadSliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceDefaultItem,
      ImageWithTextSliceImageRightPrimary,
      ImageWithTextSliceImageRightItem,
      ImageWithTextSliceImageLeftWithBackgroundPrimary,
      ImageWithTextSliceImageLeftWithBackgroundItem,
      ImageWithTextSliceImageRightLargePrimary,
      ImageWithTextSliceImageRightLargeItem,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      ImageWithTextSliceImageRight,
      ImageWithTextSliceImageLeftWithBackground,
      ImageWithTextSliceImageRightLarge,
      PhotoGallerySlice,
      PhotoGallerySliceDefaultPrimary,
      PhotoGallerySliceDefaultItem,
      PhotoGallerySliceVerticalPrimary,
      PhotoGallerySliceVerticalItem,
      PhotoGallerySliceVariation,
      PhotoGallerySliceDefault,
      PhotoGallerySliceVertical,
      PricingSlice,
      PricingSliceDefaultPrimary,
      PricingSliceDefaultItem,
      PricingSliceVariation,
      PricingSliceDefault,
      SimpleTextSlice,
      SimpleTextSliceDefaultPrimary,
      SimpleTextSliceVariation,
      SimpleTextSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceDefaultItem,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
    };
  }
}
