// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  feature: dynamic(() => import("./Feature")),
  grid_layout: dynamic(() => import("./GridLayout")),
  hero: dynamic(() => import("./Hero")),
  image_download: dynamic(() => import("./ImageDownload")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  photo_gallery: dynamic(() => import("./PhotoGallery")),
  pricing: dynamic(() => import("./Pricing")),
  simple_text: dynamic(() => import("./SimpleText")),
  testimonial: dynamic(() => import("./Testimonial")),
};
